### ISSUE TITLE
Calibrated N(z) from reweighted COSMOS data

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/HyperSupremeStructure-HSC-LSS#18]
Write a code that:
1- Works out magnitude weights for COSMOS 30-band data.
2- Uses the weighted COSMOS 30-band data to generate N(z)s for a given set of cuts.

Ideally we'd like to implement this in [cat_sampler.py](https://github.com/LSSTDESC/HyperSupremeStructure-HSC-LSS/blob/master/cat_sampler.py), but this may be a bit trickier than issue #17 , so we should exercise more freedom here.

Tagging: @adam-broussard (and Zahra as soon as she gets added as contributor) as people spearheading this.

**Comment by zahragomes** [comment]
> Write a code that:
> 1- Works out magnitude weights for COSMOS 30-band data.
> 2- Uses the weighted COSMOS 30-band data to generate N(z)s for a given set of cuts.
> 
> Ideally we'd like to implement this in [cat_sampler.py](https://github.com/LSSTDESC/HyperSupremeStructure-HSC-LSS/blob/master/cat_sampler.py), but this may be a bit trickier than issue #17 , so we should exercise more freedom here.
> 
> Tagging: @adam-broussard (and Zahra as soon as she gets added as contributor) as people spearheading this.

Here's the result I got when I did the re-weighting on based on the HSC COSMOS field. 
![n(z)_20nn_cosmos_field](https://user-images.githubusercontent.com/25539966/46290144-f1537900-c582-11e8-8b85-6ce865d078ba.png)

**Comment by damonge** [comment]
That's great @zahragomes!

Would it be possible to redo this for the 4 redshift bins currently stated in the [wiki](https://github.com/LSSTDESC/HyperSupremeStructure-HSC-LSS/wiki)? The bin edges would be: 0.15, 0.50, 0.75, 1.0, 1.5. We have decided to do the binning using the z_best quantity for the ephor_ab code.

Also, it would be good to see the code that does this, and possibly integrate it with the rest of the pipeline.

**Comment by zahragomes** [comment]
Here are the results in redshift bins:
![015-05](https://user-images.githubusercontent.com/25539966/46342606-18698380-c633-11e8-9c6f-4efc26fe5b84.png)

![05-075](https://user-images.githubusercontent.com/25539966/46342658-4353d780-c633-11e8-9be1-e64cd4850a2b.png)
![075-10](https://user-images.githubusercontent.com/25539966/46342668-48188b80-c633-11e8-98e1-8e53968b907d.png)
![10-15](https://user-images.githubusercontent.com/25539966/46342682-4cdd3f80-c633-11e8-917c-84165c1e13af.png)
![all_bins](https://user-images.githubusercontent.com/25539966/46342696-549ce400-c633-11e8-84a0-62bbf2f93279.png)

**Comment by egawiser** [comment]
Nice results and presentation, @zahragomes!  This isn't anybody's fault, but the redshift distributions we're getting are all wrong in a common way - they show a bump at z~3 and troughs at z~2.5 and z~3.8.  Those features are presumably caused by systematics in the 30-band photo-z's leading to larger-than-LSS modulations in the reported redshift distribution.  The impact on cosmological parameter calculation might not be important - an easy way to test would be to fit a low-order polynomial to the z>2 portion of those N(z) and see how different the cosmology predictions are using the smooth curve instead at z>2.  However, my biggest concern is that degeneracies between low- and high-redshift photo-z's are often more localized than seen here.  It's typical for a 0.15<z<0.5 bin to have significant aliasing from z~3, but that should be much less common in the other bins, whereas here the high-z contamination looks remarkably constant over the bins.  What prior was used in redshift?  If the pattern is coming straight from the prior, as could happen if a prior from a tiny field like the Hubble Deep Field were used, this would make sense (but still be a misleading result).

**Comment by damonge** [comment]
Yes, I think we're still missing something here. I've pasted a plot of the N(z)s we get from stacking below. To some extent we should be getting something that is relatively similar to Fig. 3 of https://arxiv.org/pdf/1809.09148.pdf (the exact bin edges are different, but whatever). We don't seem to be quite there yet (e.g. in terms of the feature at z=3), although the HSC plot doesn't really extend al the way to z=3.

It might be worth going through the exact cuts that have been made on the data to see if we've missed something. I'll try to have a look tomorrow, but if we don't see something obvious, we could ask our HSC guys for advice.

![ephor_stacking](https://user-images.githubusercontent.com/8809493/46372995-a6ba2580-c684-11e8-97e0-4c3ff3eb6a08.png)

Now, regardless of this, I think the N(z)s @zahragomes is getting are noticeably different from the stacked ones. I wouldn't expect both to be the same, obviously, but it does seem like the reweighted COSMOS ones are a bit more spread out. It would be good to see whether any of this could come from contamination in the angular matching used to assign HSC bands to the COSMOS data. I'll try to go through the code, but we could have a chat this week to brainstorm this.

**Comment by damonge** [comment]
@zahragomes has produced some new results regarding this, which will be posted below. In the meantime, here are the main tasks we've identified for the sprint week:

- [ ] Compare N(z) from COSMOS 30-band and from stacking (with the same binning etc.) @zahragomes and @adam-broussard will work on this. It'd be good to get some error bars from the COSMOS estimates in order to do the comparison.
- [ ] Investigate bump at z~3 from HSC paper (and bothering HSC people). I will work on this (but others are also welcome to investigate!).

**Comment by zahragomes** [comment]
After fixing the problem with the matching of COSMOS galaxies to HSC galaxies (I am now finding the nearest COSMOS galaxy to each HSC galaxy and only using it if it is within a 1arcsec radius), these are the new N(z) plots:

![n z 15-5](https://user-images.githubusercontent.com/25539966/46752641-abe72800-ccb5-11e8-8479-d32acf878361.png)
![n z 5_75](https://user-images.githubusercontent.com/25539966/46752620-996cee80-ccb5-11e8-93bd-8843d5f84391.png)
![n z 75_1](https://user-images.githubusercontent.com/25539966/46752625-9c67df00-ccb5-11e8-8f0c-79b2f1e4d834.png)
![n z 1_15](https://user-images.githubusercontent.com/25539966/46752627-9e31a280-ccb5-11e8-97f0-4d1d462b6972.png)
![n z _all_z_in_bins](https://user-images.githubusercontent.com/25539966/46752631-a093fc80-ccb5-11e8-9018-26117456da96.png)

**Comment by damonge** [comment]
OK, I've been looking into the bump at z=3, and I have 2 updates:
1. I've looked at the HSC cuts. One thing we weren't doing is cutting in S/N, so I've implemented a 10-sigma cut in i and the requirement that sources should be also detected above 5-sigma in two of the other bands.
2. Note that it is actually not possible to implement the same cuts that they have in the papers, because not all the information is in the public data release. The missing information is mostly about shape measurements, which is not a problem, but there are some deblending variables we don't have, which might be relevant. Here's the list of cuts we implement and those we can't (with 3 red dots for those that could be relevant).
![cuts](https://user-images.githubusercontent.com/8809493/46797927-6162bb80-cd48-11e8-85a7-90d3dedd118d.png)
3. After implementing the S/N cuts, I've recomputed the N(z)s for the same bins they use in the HSC paper (see Fig. 3 of https://arxiv.org/pdf/1809.09148.pdf), and I get the following plot:
![nzs](https://user-images.githubusercontent.com/8809493/46797991-8e16d300-cd48-11e8-9c23-4202a717a254.png)
Note that the bump is still there for the first bin, but it goes away for all the other ones. I'm gonna ping Hironao/Rachel about this on slack.
4. I've only been able to compute the z_MC-based N(z)s, since due to the new cuts we don't have matched pdfs. I'm running the matching now and hopefully I'll succeed, but I'll ping @humnaawan if I don't.
5. It'd be good to recreate the COSMOS N(z)s for the new HSC catalogs (same path as before), and do the comparison for those @zahragomes .

**Comment by damonge** [comment]
OK, I've managed to match the pdfs, so @humnaawan can ignore the above

**Comment by zahragomes** [comment]
Here are the corresponding COSMOS N(z)s

![sn_cut_n z _all_cut_4](https://user-images.githubusercontent.com/25539966/46803621-6def1000-cd58-11e8-9609-9cb93b25bf7b.png)

**Comment by damonge** [comment]
OK, first quick comparison between stacks and COSMOS. Will refine later on:
![nzs](https://user-images.githubusercontent.com/8809493/47427754-3422fe00-d789-11e8-8ad9-72eb37542a6e.png)

**Comment by egawiser** [comment]
That comparison does look good.  I wonder if the fluctuations in COSMOS might reflect actual LSS - if not, the smoother version seems more believable.  But that generates another question:  do we *want* N(z) that are sensitive to realized LSS?  I would naively think that the cosmological model predictions for angular P(k) should be derived from smooth N(z) that don't have bumps for overdensities.

**Comment by damonge** [comment]
This has been implemented in the pipeline (thanks @zahragomes), and here are some comparisons with the pdf stacks.
[nz_comp_b1.pdf](https://github.com/LSSTDESC/HyperSupremeStructure-HSC-LSS/files/2515265/nz_comp_b1.pdf)
[nz_comp_b2.pdf](https://github.com/LSSTDESC/HyperSupremeStructure-HSC-LSS/files/2515266/nz_comp_b2.pdf)
[nz_comp_b3.pdf](https://github.com/LSSTDESC/HyperSupremeStructure-HSC-LSS/files/2515267/nz_comp_b3.pdf)
[nz_comp_b4.pdf](https://github.com/LSSTDESC/HyperSupremeStructure-HSC-LSS/files/2515268/nz_comp_b4.pdf)
In all cases things agree relatively well, with the pdf stacks showing slightly longer tails (which are to be expected, I believe).

I'll close this issue now.
