### ISSUE TITLE
Galaxy selection (HSC clean photometry flags)

### ISSUE THREAD

**Issue by anicola** [LSSTDESC/HyperSupremeStructure-HSC-LSS#35]
The flags for obtaining objects with clean photometry are described in Aihara et al., 2018 (p. 12/13, Sec. 4.3) and in SQL form, they are:

```
 -- Centroid algorithm succeeded in all bands
 NOT forced.gcentroid_sdss_flags
 AND NOT forced.rcentroid_sdss_flags
 AND NOT forced.icentroid_sdss_flags
 AND NOT forced.zcentroid_sdss_flags
 AND NOT forced.ycentroid_sdss_flags

 -- CModel flux algorithm succeeded in all bands
 AND NOT forced.gcmodel_flux_flags
 AND NOT forced.rcmodel_flux_flags
 AND NOT forced.icmodel_flux_flags
 AND NOT forced.zcmodel_flux_flags
 AND NOT forced.ycmodel_flux_flags

 -- PSF flux algorithm succeeded in all bands
 AND NOT forced.gflux_psf_flags
 AND NOT forced.rflux_psf_flags
 AND NOT forced.iflux_psf_flags
 AND NOT forced.zflux_psf_flags
 AND NOT forced.yflux_psf_flags

 -- Not at the edges of images
 AND NOT forced.gflags_pixel_edge
 AND NOT forced.rflags_pixel_edge
 AND NOT forced.iflags_pixel_edge
 AND NOT forced.zflags_pixel_edge
 AND NOT forced.yflags_pixel_edge

 -- Center 3x3 pixels are not interpolated
 AND NOT forced.gflags_pixel_interpolated_center
 AND NOT forced.rflags_pixel_interpolated_center
 AND NOT forced.iflags_pixel_interpolated_center
 AND NOT forced.zflags_pixel_interpolated_center
 AND NOT forced.yflags_pixel_interpolated_center

 -- Center 3x3 pixels are not saturated
 AND NOT forced.gflags_pixel_saturated_center
 AND NOT forced.rflags_pixel_saturated_center
 AND NOT forced.iflags_pixel_saturated_center
 AND NOT forced.zflags_pixel_saturated_center
 AND NOT forced.yflags_pixel_saturated_center

 -- Center 3x3 pixels are not contaminated by cosmic rays
 AND NOT forced.gflags_pixel_cr_center
 AND NOT forced.rflags_pixel_cr_center
 AND NOT forced.iflags_pixel_cr_center
 AND NOT forced.zflags_pixel_cr_center
 AND NOT forced.yflags_pixel_cr_center

 -- Not on bad pixels of CCDs
 AND NOT forced.gflags_pixel_bad
 AND NOT forced.rflags_pixel_bad
 AND NOT forced.iflags_pixel_bad
 AND NOT forced.zflags_pixel_bad
 AND NOT forced.yflags_pixel_bad
```

The shear catalog has been created by applying these flags only in the i-band. This means that some objects will pass the WL cuts, even though some of these flags are set in another band or they don't have data in some photometric bands. 
I have found this looking at the non-public HSC data and I suspect that the fraction of such objects will be smaller for the public data. Nevertheless, I would suggest to revisit the galaxy selection and check if this has an effect on results.
Related to that, there is the question of the star mask. As far as I can tell, the data used has the Arcturus star mask applied. This mask excludes bright galaxies, which might affect clustering measurements (I saw hints of this in the non-public data). I am not sure how to best do this, as the updated star mask is not public, but I suggest that we look into this as well.

**Comment by damonge** [comment]
Will download new clean catalogs imposing this cuts and post some plots here when I get the new data

**Comment by damonge** [comment]
(will do as soon as Cori is back up)

**Comment by egawiser** [comment]
That sounds very reasonable to me.  I looked through the full list of cuts, and I don’t see any good reason why legitimate galaxies should fail any of them.  Probably at least one of those photometry algorithms is failing for very dim galaxies, and that’s why so many sources are affected.  One could also cluster the 3% of i<25.5 galaxies that are removed - if they look reasonably similar but lower amplitude and noisier, they might have been usable, but if there are obvious systematics, we’ll be happy to have removed them.  (You could even measure the cross-correlation, if you really *love* LSS… 😏 )

**Comment by damonge** [comment]
Here is the comparison of the effect on the final power spectrum (showing the difference between our fiducial cuts and these more stringent ones):
![compare_cuts](https://user-images.githubusercontent.com/8809493/50516130-e4bac000-0aa0-11e9-9b85-a49a6dc69e70.png)

The effect is really small within the range of scales we'll use (ell<2000-3000). However, on very small scales (ell~10K) you do see some >1-sigma effects, so I'd suggest using the more strict cuts as fiducials, and showing this as part of our systematics discussion.

Thoughts?

**Comment by damonge** [comment]
Alright, I've documented all of this in the wiki. I'll close this issue, but anyone should feel free to reopen it if you're still not happy about it.
